use ssas;

DROP TABLE IF EXISTS USER_HOBBY;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS EMAIL_CONFIRMATION;
DROP TABLE IF EXISTS FRIEND_REQUEST;
DROP TABLE IF EXISTS SESSION;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS FRIEND;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID int NOT NULL auto_increment,
  NAME Varchar(255) NOT NULL,
  ADDRESS Varchar(255),
  EMAIL Varchar(255) NOT NULL,
  PASSWORD Varchar(255) NOT NULL,
  SALT varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (ID),
  UNIQUE (Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FRIEND (
  USER1 int NOT NULL,
  USER2 int NOT NULL,
  RELATIONSHIP Enum('ROMANCE', 'BROMANCE', 'FRIENDSHIP') NOT NULL DEFAULT 'FRIENDSHIP',
  PRIMARY KEY (USER1, USER2),
  CONSTRAINT `FK_FRIEND_USER1` FOREIGN KEY (`USER1`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_FRIEND_USER2` FOREIGN KEY (`USER2`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ADMIN (
	USER int NOT NULL,
	PRIMARY KEY (USER),
	CONSTRAINT `FK_ADMIN_USER` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SESSION (
	SESSION_KEY varchar(36) NOT NULL,
	USER int NOT NULL,
	PRIMARY KEY (SESSION_KEY),
	CONSTRAINT `FK_SESSION_USER` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FRIEND_REQUEST (
	FROM_USER int NOT NULL,
	TO_USER int NOT NULL,
	RELATIONSHIP Enum('ROMANCE', 'BROMANCE', 'FRIENDSHIP') NOT NULL DEFAULT 'FRIEND',
	PRIMARY KEY (FROM_USER, TO_USER),
	CONSTRAINT `FK_FRIEND_REQUEST_USER1` FOREIGN KEY (`FROM_USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_FRIEND_REQUEST_USER2` FOREIGN KEY (`TO_USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EMAIL_CONFIRMATION (
	GUID varchar(36) NOT NULL,
	USER int NOT NULL,
	PRIMARY KEY (GUID),
	CONSTRAINT `FK_EMAIL_CONFIRMATION_USER` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE HOBBY (
	ID int NOT NULL auto_increment,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_HOBBY (
	USER int NOT NULL,
	HOBBY int NOT NULL,
	PRIMARY KEY (USER, HOBBY),
	CONSTRAINT `FK_USER_HOBBY_USER` FOREIGN KEY (`USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_HOBBY_HOBBY` FOREIGN KEY (`HOBBY`) REFERENCES `HOBBY` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
