DROP TABLE IF EXISTS UserHobby;
DROP TABLE IF EXISTS Hobby;
DROP TABLE IF EXISTS EmailConfirmation;
DROP TABLE IF EXISTS FriendRequest;
DROP TABLE IF EXISTS Session;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Friend;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
  ID int NOT NULL auto_increment,
  Name Varchar(255) NOT NULL,
  Address Varchar(255),
  Email Varchar(255) NOT NULL,
  Password Varchar(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Friend (
  User1 int NOT NULL,
  User2 int NOT NULL,
  Status Enum('Relationship', 'Friend') NOT NULL DEFAULT 'Friend',
  PRIMARY KEY (User1, User2),
  CONSTRAINT `fk_friend_User1` FOREIGN KEY (`User1`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_User2` FOREIGN KEY (`User2`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Admin (
	User int NOT NULL,
	PRIMARY KEY (User),
	CONSTRAINT `fk_admin_User` FOREIGN KEY (`User`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Session (
	SessionKey varchar(36) NOT NULL,
	User int NOT NULL,
	PRIMARY KEY (SessionKey),
	CONSTRAINT `fk_session_User` FOREIGN KEY (`User`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FriendRequest (
	FromUser int NOT NULL,
	ToUser int NOT NULL,
	Status Enum('Relationship', 'Friend') NOT NULL DEFAULT 'Friend',
	PRIMARY KEY (FromUser, ToUser),
	CONSTRAINT `fk_friendRequest_User1` FOREIGN KEY (`FromUser`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendRequest_User2` FOREIGN KEY (`ToUser`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EmailConfirmation (
	GUID varchar(36) NOT NULL,
	User int NOT NULL,
	PRIMARY KEY (GUID),
	CONSTRAINT `fk_emailConfirmation_User` FOREIGN KEY (`User`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Hobby (
	ID int NOT NULL auto_increment,
	Name varchar(255) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE UserHobby (
	User int NOT NULL,
	Hobby int NOT NULL,
	PRIMARY KEY (User, Hobby),
	CONSTRAINT `fk_userHobby_User` FOREIGN KEY (`User`) REFERENCES `User` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_userHobby_Hobby` FOREIGN KEY (`Hobby`) REFERENCES `Hobby` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
